/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.7 ***
*/

package mod10k.generation.structures;

import java.util.Random;

import net.minecraft.src.Block;
import net.minecraft.src.World;
import net.minecraft.src.WorldGenerator;

public class House1 extends WorldGenerator {
	public House1() {
	}

	public boolean generate(World world, Random rand, int i, int j, int k) {
		world.setBlock(i + 0, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 12, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 13, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 0, j + 5, k + 0, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 0, j + 5, k + 2, -122);
		world.setBlock(i + 0, j + 5, k + 3, -122);
		world.setBlock(i + 0, j + 5, k + 4, -122);
		world.setBlockAndMetadata(i + 0, j + 5, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 0, j + 5, k + 6, -122);
		world.setBlock(i + 0, j + 5, k + 7, -122);
		world.setBlock(i + 0, j + 5, k + 8, -122);
		world.setBlockAndMetadata(i + 0, j + 5, k + 9, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 0, j + 5, k + 10, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 1, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 1, j + 0, k + 1, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 2, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 3, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 4, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 5, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 6, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 8, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 1, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 1, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 8, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 1, k + 10, Block.fence.blockID);
		world.setBlock(i + 1, j + 1, k + 11, Block.fence.blockID);
		world.setBlock(i + 1, j + 1, k + 12, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 1, k + 13, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 3, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 4, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 2, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 6, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 8, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 2, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 13, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 8, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 10, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 11, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 12, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 4, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 4, k + 3, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 4, k + 4, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 4, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 4, k + 6, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 4, k + 8, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 4, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 5, k + 0, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 5, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 5, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 7, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 8, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 5, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 5, k + 10, Block.wood.blockID, 9);
		world.setBlock(i + 1, j + 6, k + 1, -122);
		world.setBlock(i + 1, j + 6, k + 2, -122);
		world.setBlock(i + 1, j + 6, k + 3, -122);
		world.setBlock(i + 1, j + 6, k + 4, -122);
		world.setBlock(i + 1, j + 6, k + 5, -122);
		world.setBlock(i + 1, j + 6, k + 6, -122);
		world.setBlock(i + 1, j + 6, k + 7, -122);
		world.setBlock(i + 1, j + 6, k + 8, -122);
		world.setBlock(i + 1, j + 6, k + 9, -122);
		world.setBlock(i + 2, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 2, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 2, j + 0, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 8, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 2, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 2, j + 1, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 1, k + 2, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 3, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 4, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 5, Block.chest.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 6, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 7, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 8, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 1, k + 10, -122, 3);
		world.setBlock(i + 2, j + 1, k + 13, Block.fence.blockID);
		world.setBlock(i + 2, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 2, j + 2, k + 9, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 2, j + 3, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 3, k + 2, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 3, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 4, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 5, Block.chest.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 6, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 7, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 8, -122, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 3, k + 10, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 2, j + 3, k + 11, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 2, j + 3, k + 12, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 2, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 2, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 2, j + 4, k + 9, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 2, j + 5, k + 0, -122, 2);
		world.setBlockAndMetadata(i + 2, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 5, k + 9, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 5, k + 10, -122, 3);
		world.setBlockAndMetadata(i + 2, j + 6, k + 1, -122, 2);
		world.setBlockAndMetadata(i + 2, j + 6, k + 9, -122, 3);
		world.setBlockAndMetadata(i + 2, j + 7, k + 2, -122, 2);
		world.setBlock(i + 2, j + 7, k + 3, -122);
		world.setBlock(i + 2, j + 7, k + 4, -122);
		world.setBlock(i + 2, j + 7, k + 5, -122);
		world.setBlock(i + 2, j + 7, k + 6, -122);
		world.setBlock(i + 2, j + 7, k + 7, -122);
		world.setBlockAndMetadata(i + 2, j + 7, k + 8, -122, 3);
		world.setBlock(i + 3, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 3, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 3, j + 0, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 0, k + 3, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 3, j + 0, k + 4, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 3, j + 0, k + 5, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 3, j + 0, k + 6, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 3, j + 0, k + 7, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 3, j + 0, k + 8, Block.planks.blockID, 1);
		world.setBlock(i + 3, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 3, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 3, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 3, j + 1, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 1, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 1, k + 13, Block.fence.blockID);
		world.setBlock(i + 3, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 3, j + 2, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 3, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 3, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 3, k + 10, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 3, k + 11, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 3, k + 12, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 3, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 3, j + 4, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 0, -122, 2);
		world.setBlockAndMetadata(i + 3, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 3, j + 5, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 10, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 6, k + 1, -122, 2);
		world.setBlockAndMetadata(i + 3, j + 6, k + 9, -122, 3);
		world.setBlockAndMetadata(i + 3, j + 7, k + 2, -122, 2);
		world.setBlockAndMetadata(i + 3, j + 7, k + 8, -122, 3);
		world.setBlockAndMetadata(i + 3, j + 8, k + 3, -122, 2);
		world.setBlock(i + 3, j + 8, k + 4, -122);
		world.setBlock(i + 3, j + 8, k + 5, -122);
		world.setBlock(i + 3, j + 8, k + 6, -122);
		world.setBlockAndMetadata(i + 3, j + 8, k + 7, -122, 3);
		world.setBlock(i + 4, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 4, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 4, j + 0, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 3, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 4, j + 0, k + 4, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 4, j + 0, k + 5, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 4, j + 0, k + 6, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 4, j + 0, k + 7, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 4, j + 0, k + 8, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 4, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 4, j + 1, k + 13, Block.fenceGate.blockID);
		world.setBlockAndMetadata(i + 4, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 3, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 3, k + 10, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 3, k + 11, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 3, k + 12, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 4, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 4, j + 4, k + 9, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 4, j + 5, k + 0, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 5, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 9, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 5, k + 10, -122, 3);
		world.setBlockAndMetadata(i + 4, j + 6, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 7, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 8, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 6, k + 9, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 7, k + 2, -122, 2);
		world.setBlockAndMetadata(i + 4, j + 7, k + 8, -122, 3);
		world.setBlockAndMetadata(i + 4, j + 8, k + 3, -122, 2);
		world.setBlockAndMetadata(i + 4, j + 8, k + 4, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 8, k + 5, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 8, k + 6, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 4, j + 8, k + 7, -122, 3);
		world.setBlock(i + 5, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 5, j + 0, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 0, k + 3, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 5, j + 0, k + 4, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 5, j + 0, k + 5, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 5, j + 0, k + 6, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 5, j + 0, k + 7, Block.cloth.blockID, 13);
		world.setBlockAndMetadata(i + 5, j + 0, k + 8, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 5, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 5, j + 1, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 1, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 1, k + 13, Block.fence.blockID);
		world.setBlock(i + 5, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 5, j + 2, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 3, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 3, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 3, k + 10, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 3, k + 11, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 3, k + 12, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 5, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 5, j + 4, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 0, -122, 2);
		world.setBlockAndMetadata(i + 5, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 5, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 10, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 6, k + 1, -122, 2);
		world.setBlockAndMetadata(i + 5, j + 6, k + 9, -122, 3);
		world.setBlockAndMetadata(i + 5, j + 7, k + 2, -122, 2);
		world.setBlockAndMetadata(i + 5, j + 7, k + 8, -122, 3);
		world.setBlockAndMetadata(i + 5, j + 8, k + 3, -122, 1);
		world.setBlockAndMetadata(i + 5, j + 8, k + 4, -122, 1);
		world.setBlockAndMetadata(i + 5, j + 8, k + 5, -122, 1);
		world.setBlockAndMetadata(i + 5, j + 8, k + 6, -122, 1);
		world.setBlockAndMetadata(i + 5, j + 8, k + 7, -122, 3);
		world.setBlock(i + 6, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 6, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 6, j + 0, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 8, Block.planks.blockID, 1);
		world.setBlock(i + 6, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 6, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 6, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 6, j + 1, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 1, k + 2, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 3, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 4, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 5, Block.chest.blockID, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 6, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 7, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 8, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 1, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 1, k + 10, -122, 3);
		world.setBlock(i + 6, j + 1, k + 13, Block.fence.blockID);
		world.setBlock(i + 6, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 6, j + 2, k + 9, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 6, j + 3, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 3, k + 2, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 3, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 4, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 5, Block.chest.blockID, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 6, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 7, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 8, -122, 4);
		world.setBlockAndMetadata(i + 6, j + 3, k + 9, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 3, k + 10, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 3, k + 11, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 3, k + 12, Block.woodSingleSlab.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 6, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 6, j + 4, k + 9, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 6, j + 5, k + 0, -122, 2);
		world.setBlockAndMetadata(i + 6, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 6, j + 5, k + 9, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 6, j + 5, k + 10, -122, 3);
		world.setBlockAndMetadata(i + 6, j + 6, k + 1, -122, 2);
		world.setBlockAndMetadata(i + 6, j + 6, k + 9, -122, 3);
		world.setBlockAndMetadata(i + 6, j + 7, k + 2, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 3, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 4, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 5, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 6, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 7, -122, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 8, -122, 3);
		world.setBlock(i + 7, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 7, j + 0, k + 1, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 2, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 3, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 4, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 5, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 6, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 8, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 9, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 7, j + 0, k + 10, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 0, k + 11, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 0, k + 12, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 0, k + 13, Block.planks.blockID, 1);
		world.setBlock(i + 7, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 7, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 8, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 1, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 1, k + 10, Block.fence.blockID);
		world.setBlock(i + 7, j + 1, k + 11, Block.fence.blockID);
		world.setBlock(i + 7, j + 1, k + 12, Block.fence.blockID);
		world.setBlockAndMetadata(i + 7, j + 1, k + 13, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 2, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 3, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 4, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 7, j + 2, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 2, k + 6, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 8, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 7, j + 2, k + 9, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 2, k + 13, Block.fence.blockID);
		world.setBlockAndMetadata(i + 7, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 8, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 10, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 11, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 12, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 3, k + 13, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 4, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 4, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 4, k + 3, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 4, k + 4, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 7, j + 4, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 7, j + 4, k + 6, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 4, k + 8, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 7, j + 4, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 0, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 7, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 8, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 5, k + 9, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 10, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 7, j + 6, k + 1, -122, 2);
		world.setBlockAndMetadata(i + 7, j + 6, k + 2, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 3, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 4, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 5, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 6, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 7, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 8, -122, 1);
		world.setBlockAndMetadata(i + 7, j + 6, k + 9, -122, 1);
		world.setBlock(i + 8, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 12, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 13, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 14, Block.grass.blockID);
		world.setBlockAndMetadata(i + 8, j + 5, k + 0, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 5, k + 2, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 3, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 4, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 5, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 5, k + 6, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 7, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 8, -122, 1);
		world.setBlockAndMetadata(i + 8, j + 5, k + 9, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 5, k + 10, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 4, j + 1, k + 9, Block.doorWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 9, Block.doorWood.blockID, 8);

		return true;
	}
}