/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.7 ***
*/

package mod10k;

import net.minecraft.src.*;
import java.util.Random;

public class StructureGenHouse_4 extends WorldGenerator
{
	public StructureGenHouse_4()
	{
	}

	public boolean generate(World world, Random rand, int i, int j, int k)
	{
		world.setBlock(i + 0, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 0, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 1, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 1, j + 0, k + 1, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 2, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 3, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 4, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 5, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 6, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 8, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 9, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 10, Block.dirt.blockID);
		world.setBlock(i + 1, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 1, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 8, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 9, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 10, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 1, k + 11, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 3, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 2, k + 4, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 5, Block.thinGlass.blockID);
		world.setBlock(i + 1, j + 2, k + 6, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 1, j + 2, k + 7, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 2, k + 8, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 9, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 10, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 3, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 3, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 3, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 3, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 3, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 3, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 4, k + 7, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 2, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 2, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 2, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 2, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 2, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 2, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 2, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 2, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 2, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 2, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 2, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 2, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 2, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 1, k + 2, Block.bookShelf.blockID);
		world.setBlock(i + 2, j + 1, k + 3, Block.bookShelf.blockID);
		world.setBlock(i + 2, j + 1, k + 4, Block.fence.blockID);
		world.setBlock(i + 2, j + 1, k + 5, Block.bookShelf.blockID);
		world.setBlock(i + 2, j + 1, k + 6, Block.bookShelf.blockID);
		world.setBlockAndMetadata(i + 2, j + 1, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 2, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 2, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 4, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 4, k + 7, Block.planks.blockID, 1);
		world.setBlock(i + 3, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 3, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 3, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 3, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 3, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 3, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 3, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 3, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 3, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 3, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 3, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 3, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 3, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 3, j + 1, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 3, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 3, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 3, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 3, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 3, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlock(i + 3, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 3, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 3, j + 5, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 7, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 4, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 4, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 4, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 4, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 4, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 4, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 4, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 4, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 4, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 4, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 4, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 4, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 4, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 1, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 4, j + 2, k + 7, Block.wood.blockID, 1);
		world.setBlock(i + 4, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 4, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 4, j + 5, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 5, k + 7, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 5, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 5, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 5, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 5, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 5, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 5, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 5, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 5, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 1, k + 2, Block.bed.blockID, 10);
		world.setBlockAndMetadata(i + 5, j + 1, k + 3, Block.bed.blockID, 2);
		world.setBlockAndMetadata(i + 5, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 5, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 5, j + 5, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 5, k + 7, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 6, k + 7, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 6, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 6, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 6, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 6, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 6, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 6, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 6, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 6, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 6, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 6, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 6, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 6, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 6, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 6, j + 1, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 6, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 6, j + 2, k + 7, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 6, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 6, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlock(i + 6, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 6, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 6, j + 5, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 7, Block.planks.blockID, 1);
		world.setBlock(i + 7, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 7, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 7, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 7, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 7, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 7, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 7, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 7, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 7, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 7, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 7, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 7, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 7, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 7, j + 1, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 7, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 7, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 7, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 7, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlock(i + 7, j + 4, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 7, j + 4, k + 7, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 7, j + 5, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 7, j + 5, k + 7, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 8, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 1, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 8, j + 0, k + 2, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 8, j + 0, k + 3, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 8, j + 0, k + 4, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 8, j + 0, k + 5, Block.cloth.blockID, 8);
		world.setBlockAndMetadata(i + 8, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 8, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 8, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 8, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 8, j + 1, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 8, j + 1, k + 2, Block.bookShelf.blockID);
		world.setBlock(i + 8, j + 1, k + 3, Block.fence.blockID);
		world.setBlock(i + 8, j + 1, k + 4, Block.fence.blockID);
		world.setBlock(i + 8, j + 1, k + 5, Block.bookShelf.blockID);
		world.setBlockAndMetadata(i + 8, j + 1, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 1, k + 11, Block.wood.blockID, 5);
		world.setBlock(i + 8, j + 2, k + 1, Block.thinGlass.blockID);
		world.setBlock(i + 8, j + 2, k + 7, Block.thinGlass.blockID);
		world.setBlock(i + 8, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 8, j + 3, k + 1, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 3, k + 7, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 8, j + 4, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 3, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 5, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 6, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 8, j + 4, k + 7, Block.planks.blockID, 1);
		world.setBlock(i + 9, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 9, j + 0, k + 1, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 2, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 3, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 4, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 5, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 9, j + 0, k + 6, Block.cloth.blockID, 8);
		world.setBlock(i + 9, j + 0, k + 7, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 8, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 9, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 10, Block.dirt.blockID);
		world.setBlock(i + 9, j + 0, k + 11, Block.dirt.blockID);
		world.setBlockAndMetadata(i + 9, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 1, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 1, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 1, k + 8, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 9, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 10, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 1, k + 11, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 9, j + 2, k + 2, Block.thinGlass.blockID);
		world.setBlock(i + 9, j + 2, k + 3, Block.thinGlass.blockID);
		world.setBlock(i + 9, j + 2, k + 4, Block.thinGlass.blockID);
		world.setBlockAndMetadata(i + 9, j + 2, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 2, k + 7, Block.wood.blockID, 1);
		world.setBlock(i + 9, j + 2, k + 8, Block.fence.blockID);
		world.setBlock(i + 9, j + 2, k + 9, Block.fence.blockID);
		world.setBlock(i + 9, j + 2, k + 10, Block.fence.blockID);
		world.setBlock(i + 9, j + 2, k + 11, Block.fence.blockID);
		world.setBlockAndMetadata(i + 9, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 3, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 3, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 3, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 3, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 3, k + 6, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 9, j + 3, k + 7, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 9, j + 4, k + 7, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 10, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 10, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 10, j + 1, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 10, j + 1, k + 11, Block.fenceGate.blockID, 2);
		world.setBlock(i + 11, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 11, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 11, j + 1, k + 5, Block.fence.blockID);
		world.setBlock(i + 11, j + 1, k + 11, Block.fence.blockID);
		world.setBlock(i + 12, j + 0, k + 0, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 1, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 2, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 3, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 4, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 5, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 6, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 7, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 8, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 9, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 10, Block.grass.blockID);
		world.setBlock(i + 12, j + 0, k + 11, Block.grass.blockID);
		world.setBlock(i + 12, j + 1, k + 5, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 6, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 7, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 8, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 9, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 10, Block.fence.blockID);
		world.setBlock(i + 12, j + 1, k + 11, Block.fence.blockID);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 1, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 4, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 0, j + 2, k + 7, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 0, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 1, j + 3, k + 11, Block.torchWood.blockID, 5);
		world.setBlockAndMetadataWithNotify(i + 2, j + 2, k + 4, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 6, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 4, j + 2, k + 8, Block.torchWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 0, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 4, j + 5, k + 8, Block.torchWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 1, k + 7, Block.doorWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 0, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 2, Block.torchWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 7, Block.doorWood.blockID, 8);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 6, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 6, j + 2, k + 8, Block.torchWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 0, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 6, j + 5, k + 8, Block.torchWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 8, j + 2, k + 5, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 9, j + 1, k + 6, Block.doorWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 9, j + 2, k + 0, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 9, j + 2, k + 6, Block.doorWood.blockID, 8);
		world.setBlockAndMetadataWithNotify(i + 9, j + 3, k + 11, Block.torchWood.blockID, 5);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 1, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 5, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 10, j + 2, k + 7, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 12, j + 2, k + 11, Block.torchWood.blockID, 5);

		return true;
	}
}