/*
*** MADE BY MITHION'S .SCHEMATIC TO JAVA CONVERTING TOOL v1.7 ***
*/

package mod10k;

import net.minecraft.src.*;
import java.util.Random;

public class StructureGenHouse_3 extends WorldGenerator
{
	public StructureGenHouse_3()
	{
	}

	public boolean generate(World world, Random rand, int i, int j, int k)
	{
		world.setBlock(i + 0, j + 0, k + 0, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 0, j + 0, k + 1, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 0, j + 0, k + 2, Block.cobblestone.blockID);
		world.setBlock(i + 0, j + 0, k + 3, Block.cobblestone.blockID);
		world.setBlock(i + 0, j + 0, k + 4, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 0, j + 0, k + 5, Block.cobblestone.blockID);
		world.setBlock(i + 0, j + 0, k + 6, Block.cobblestone.blockID);
		world.setBlockAndMetadata(i + 0, j + 1, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 1, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 1, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 1, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 1, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 1, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 1, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 2, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 2, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 2, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 2, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 2, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 2, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 2, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 3, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 3, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 3, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 3, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 3, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 3, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 3, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 4, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 4, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 4, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 4, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 4, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 4, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 4, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 5, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 5, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 5, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 5, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 5, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 5, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 5, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 6, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 6, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 6, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 6, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 6, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 6, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 6, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 7, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 7, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 7, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 7, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 7, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 7, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 7, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 8, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 8, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 8, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 8, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 8, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 8, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 8, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 9, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 9, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 9, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 9, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 9, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 9, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 9, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 10, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 10, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 10, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 10, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 10, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 10, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 10, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 11, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 11, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 11, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 11, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 11, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 11, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 11, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 12, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 12, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 12, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 12, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 12, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 12, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 12, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 13, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 13, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 13, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 13, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 13, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 13, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 13, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 14, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 14, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 14, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 14, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 14, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 14, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 14, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 15, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 15, k + 1, Block.stone.blockID);
		world.setBlock(i + 0, j + 15, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 15, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 15, k + 4, Block.stone.blockID);
		world.setBlock(i + 0, j + 15, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 0, j + 15, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 16, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 16, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 16, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 16, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 16, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 16, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 0, j + 16, k + 6, Block.wood.blockID, 1);
		world.setBlock(i + 0, j + 17, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 0, j + 17, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 17, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 17, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 17, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 17, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 0, j + 17, k + 6, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 0, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 2, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 4, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 0, j + 19, k + 0, 0);
		world.setBlock(i + 0, j + 19, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 19, k + 2, 0);
		world.setBlock(i + 0, j + 19, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 19, k + 4, 0);
		world.setBlock(i + 0, j + 19, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 19, k + 6, 0);
		world.setBlock(i + 0, j + 20, k + 0, 0);
		world.setBlock(i + 0, j + 20, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 20, k + 2, 0);
		world.setBlock(i + 0, j + 20, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 20, k + 4, 0);
		world.setBlock(i + 0, j + 20, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 20, k + 6, 0);
		world.setBlock(i + 0, j + 21, k + 0, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 2, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 4, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 0, j + 22, k + 0, 0);
		world.setBlock(i + 0, j + 22, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 22, k + 2, 0);
		world.setBlock(i + 0, j + 22, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 22, k + 4, 0);
		world.setBlock(i + 0, j + 22, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 22, k + 6, 0);
		world.setBlock(i + 0, j + 23, k + 0, 0);
		world.setBlock(i + 0, j + 23, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 23, k + 2, 0);
		world.setBlock(i + 0, j + 23, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 23, k + 4, 0);
		world.setBlock(i + 0, j + 23, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 23, k + 6, 0);
		world.setBlock(i + 0, j + 24, k + 0, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 2, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 4, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 0, j + 25, k + 0, 0);
		world.setBlock(i + 0, j + 25, k + 1, 0);
		world.setBlock(i + 0, j + 25, k + 2, 0);
		world.setBlock(i + 0, j + 25, k + 3, 0);
		world.setBlock(i + 0, j + 25, k + 4, 0);
		world.setBlock(i + 0, j + 25, k + 5, 0);
		world.setBlock(i + 0, j + 25, k + 6, 0);
		world.setBlock(i + 0, j + 26, k + 0, 0);
		world.setBlock(i + 0, j + 26, k + 1, 0);
		world.setBlock(i + 0, j + 26, k + 2, 0);
		world.setBlock(i + 0, j + 26, k + 3, 0);
		world.setBlock(i + 0, j + 26, k + 4, 0);
		world.setBlock(i + 0, j + 26, k + 5, 0);
		world.setBlock(i + 0, j + 26, k + 6, 0);
		world.setBlock(i + 0, j + 27, k + 0, 0);
		world.setBlock(i + 0, j + 27, k + 1, 0);
		world.setBlock(i + 0, j + 27, k + 2, 0);
		world.setBlock(i + 0, j + 27, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 27, k + 4, 0);
		world.setBlock(i + 0, j + 27, k + 5, 0);
		world.setBlock(i + 0, j + 27, k + 6, 0);
		world.setBlock(i + 0, j + 28, k + 0, 0);
		world.setBlock(i + 0, j + 28, k + 1, 0);
		world.setBlock(i + 0, j + 28, k + 2, 0);
		world.setBlock(i + 0, j + 28, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 28, k + 4, 0);
		world.setBlock(i + 0, j + 28, k + 5, 0);
		world.setBlock(i + 0, j + 28, k + 6, 0);
		world.setBlock(i + 0, j + 29, k + 0, 0);
		world.setBlock(i + 0, j + 29, k + 1, Block.fence.blockID);
		world.setBlock(i + 0, j + 29, k + 2, Block.fence.blockID);
		world.setBlock(i + 0, j + 29, k + 3, Block.fence.blockID);
		world.setBlock(i + 0, j + 29, k + 4, Block.fence.blockID);
		world.setBlock(i + 0, j + 29, k + 5, Block.fence.blockID);
		world.setBlock(i + 0, j + 29, k + 6, 0);
		world.setBlock(i + 0, j + 30, k + 0, 0);
		world.setBlock(i + 0, j + 30, k + 1, 0);
		world.setBlockAndMetadata(i + 0, j + 30, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 30, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 0, j + 30, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 0, j + 30, k + 5, 0);
		world.setBlock(i + 0, j + 30, k + 6, 0);
		world.setBlock(i + 0, j + 31, k + 0, 0);
		world.setBlock(i + 0, j + 31, k + 1, 0);
		world.setBlock(i + 0, j + 31, k + 2, 0);
		world.setBlock(i + 0, j + 31, k + 3, 0);
		world.setBlock(i + 0, j + 31, k + 4, 0);
		world.setBlock(i + 0, j + 31, k + 5, 0);
		world.setBlock(i + 0, j + 31, k + 6, 0);
		world.setBlock(i + 1, j + 0, k + 0, Block.cobblestone.blockID);
		world.setBlock(i + 1, j + 0, k + 1, Block.cobblestone.blockID);
		world.setBlock(i + 1, j + 0, k + 2, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 1, j + 0, k + 3, Block.cobblestone.blockID);
		world.setBlock(i + 1, j + 0, k + 4, Block.cobblestone.blockID);
		world.setBlock(i + 1, j + 0, k + 5, Block.cobblestone.blockID);
		world.setBlock(i + 1, j + 0, k + 6, Block.cobblestoneMossy.blockID);
		world.setBlockAndMetadata(i + 1, j + 1, k + 0, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 1, j + 1, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 3, Block.chest.blockID, 5);
		world.setBlockAndMetadata(i + 1, j + 1, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 1, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 2, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 2, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 2, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 4, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 2, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 3, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 3, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 3, k + 2, -122, 5);
		world.setBlockAndMetadata(i + 1, j + 3, k + 3, Block.chest.blockID, 5);
		world.setBlockAndMetadata(i + 1, j + 3, k + 4, -122, 5);
		world.setBlock(i + 1, j + 3, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 3, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 1, j + 4, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 4, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 4, k + 2, 0);
		world.setBlock(i + 1, j + 4, k + 3, 0);
		world.setBlock(i + 1, j + 4, k + 4, 0);
		world.setBlock(i + 1, j + 4, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 4, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 5, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 5, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 5, k + 2, 0);
		world.setBlock(i + 1, j + 5, k + 4, 0);
		world.setBlock(i + 1, j + 5, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 5, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 6, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 6, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 6, k + 2, 0);
		world.setBlock(i + 1, j + 6, k + 3, 0);
		world.setBlock(i + 1, j + 6, k + 4, 0);
		world.setBlock(i + 1, j + 6, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 6, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 1, j + 7, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 7, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 7, k + 2, Block.fence.blockID);
		world.setBlock(i + 1, j + 7, k + 3, Block.fence.blockID);
		world.setBlock(i + 1, j + 7, k + 4, Block.fence.blockID);
		world.setBlock(i + 1, j + 7, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 7, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 8, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 8, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 8, k + 2, 0);
		world.setBlock(i + 1, j + 8, k + 3, 0);
		world.setBlock(i + 1, j + 8, k + 4, 0);
		world.setBlock(i + 1, j + 8, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 8, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 9, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 9, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 9, k + 2, 0);
		world.setBlock(i + 1, j + 9, k + 3, 0);
		world.setBlock(i + 1, j + 9, k + 4, 0);
		world.setBlock(i + 1, j + 9, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 9, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 1, j + 10, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 10, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 10, k + 2, 0);
		world.setBlock(i + 1, j + 10, k + 4, 0);
		world.setBlock(i + 1, j + 10, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 10, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 11, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 11, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 11, k + 2, 0);
		world.setBlock(i + 1, j + 11, k + 3, 0);
		world.setBlock(i + 1, j + 11, k + 4, 0);
		world.setBlock(i + 1, j + 11, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 11, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 12, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 12, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 12, k + 2, 0);
		world.setBlock(i + 1, j + 12, k + 3, 0);
		world.setBlock(i + 1, j + 12, k + 4, 0);
		world.setBlock(i + 1, j + 12, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 12, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 1, j + 13, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 13, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 13, k + 2, Block.fence.blockID);
		world.setBlock(i + 1, j + 13, k + 3, Block.fence.blockID);
		world.setBlock(i + 1, j + 13, k + 4, Block.fence.blockID);
		world.setBlock(i + 1, j + 13, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 13, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 14, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 14, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 14, k + 2, 0);
		world.setBlock(i + 1, j + 14, k + 3, Block.fence.blockID);
		world.setBlock(i + 1, j + 14, k + 4, 0);
		world.setBlock(i + 1, j + 14, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 14, k + 6, Block.stone.blockID);
		world.setBlock(i + 1, j + 15, k + 0, Block.stone.blockID);
		world.setBlock(i + 1, j + 15, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 15, k + 2, 0);
		world.setBlock(i + 1, j + 15, k + 3, Block.fence.blockID);
		world.setBlock(i + 1, j + 15, k + 4, 0);
		world.setBlock(i + 1, j + 15, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 15, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 1, j + 16, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 1, j + 16, k + 1, Block.fence.blockID);
		world.setBlock(i + 1, j + 16, k + 2, Block.fence.blockID);
		world.setBlock(i + 1, j + 16, k + 3, Block.fence.blockID);
		world.setBlock(i + 1, j + 16, k + 4, Block.fence.blockID);
		world.setBlock(i + 1, j + 16, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 16, k + 6, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 1, j + 17, k + 0, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 17, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 17, k + 2, -122, 5);
		world.setBlockAndMetadata(i + 1, j + 17, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 17, k + 4, -122, 5);
		world.setBlockAndMetadata(i + 1, j + 17, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 17, k + 6, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 18, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 18, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 18, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 18, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 18, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 18, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 19, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 19, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 19, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 19, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 19, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 19, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 19, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 20, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 20, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 20, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 20, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 20, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 20, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 20, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 21, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 21, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 21, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 21, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 21, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 21, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 22, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 22, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 22, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 22, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 22, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 22, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 22, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 23, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 23, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 23, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 23, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 23, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 23, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 23, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 24, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 24, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 24, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 24, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 24, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 24, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 1, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 25, k + 0, 0);
		world.setBlockAndMetadata(i + 1, j + 25, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 25, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 25, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 25, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 25, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 25, k + 6, 0);
		world.setBlock(i + 1, j + 26, k + 0, 0);
		world.setBlockAndMetadata(i + 1, j + 26, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 26, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 26, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 26, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 26, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 26, k + 6, 0);
		world.setBlock(i + 1, j + 27, k + 0, 0);
		world.setBlock(i + 1, j + 27, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 27, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 27, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 27, k + 4, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 27, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 27, k + 6, 0);
		world.setBlock(i + 1, j + 28, k + 0, 0);
		world.setBlock(i + 1, j + 28, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 28, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 28, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 28, k + 4, Block.planks.blockID, 1);
		world.setBlock(i + 1, j + 28, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 28, k + 6, 0);
		world.setBlock(i + 1, j + 29, k + 0, Block.fence.blockID);
		world.setBlock(i + 1, j + 29, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 1, j + 29, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 1, j + 29, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 29, k + 4, Block.wood.blockID, 9);
		world.setBlock(i + 1, j + 29, k + 5, Block.fence.blockID);
		world.setBlock(i + 1, j + 29, k + 6, Block.fence.blockID);
		world.setBlock(i + 1, j + 30, k + 0, 0);
		world.setBlockAndMetadata(i + 1, j + 30, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 30, k + 2, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 30, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 30, k + 4, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 1, j + 30, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 1, j + 30, k + 6, 0);
		world.setBlock(i + 1, j + 31, k + 0, 0);
		world.setBlock(i + 1, j + 31, k + 1, 0);
		world.setBlock(i + 1, j + 31, k + 2, 0);
		world.setBlock(i + 1, j + 31, k + 3, 0);
		world.setBlock(i + 1, j + 31, k + 4, 0);
		world.setBlock(i + 1, j + 31, k + 5, 0);
		world.setBlock(i + 1, j + 31, k + 6, 0);
		world.setBlock(i + 2, j + 0, k + 0, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 2, j + 0, k + 1, Block.cobblestone.blockID);
		world.setBlock(i + 2, j + 0, k + 2, Block.cobblestone.blockID);
		world.setBlock(i + 2, j + 0, k + 3, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 2, j + 0, k + 4, Block.cobblestone.blockID);
		world.setBlock(i + 2, j + 0, k + 5, Block.cobblestone.blockID);
		world.setBlock(i + 2, j + 0, k + 6, Block.cobblestoneMossy.blockID);
		world.setBlockAndMetadata(i + 2, j + 1, k + 0, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 1, k + 1, Block.chest.blockID, 3);
		world.setBlock(i + 2, j + 1, k + 2, 0);
		world.setBlock(i + 2, j + 1, k + 3, 0);
		world.setBlock(i + 2, j + 1, k + 4, 0);
		world.setBlockAndMetadata(i + 2, j + 1, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 1, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 2, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 2, k + 1, Block.fence.blockID);
		world.setBlock(i + 2, j + 2, k + 2, 0);
		world.setBlock(i + 2, j + 2, k + 3, 0);
		world.setBlock(i + 2, j + 2, k + 4, 0);
		world.setBlock(i + 2, j + 2, k + 5, Block.fence.blockID);
		world.setBlock(i + 2, j + 2, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 3, k + 0, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 3, k + 1, -122, 7);
		world.setBlock(i + 2, j + 3, k + 2, 0);
		world.setBlock(i + 2, j + 3, k + 3, 0);
		world.setBlock(i + 2, j + 3, k + 4, 0);
		world.setBlockAndMetadata(i + 2, j + 3, k + 5, -122, 6);
		world.setBlock(i + 2, j + 3, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 4, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 4, k + 1, 0);
		world.setBlock(i + 2, j + 4, k + 2, 0);
		world.setBlock(i + 2, j + 4, k + 3, 0);
		world.setBlock(i + 2, j + 4, k + 4, 0);
		world.setBlock(i + 2, j + 4, k + 5, 0);
		world.setBlockAndMetadata(i + 2, j + 4, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 5, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 5, k + 1, 0);
		world.setBlock(i + 2, j + 5, k + 2, 0);
		world.setBlock(i + 2, j + 5, k + 3, 0);
		world.setBlock(i + 2, j + 5, k + 4, 0);
		world.setBlock(i + 2, j + 5, k + 5, 0);
		world.setBlock(i + 2, j + 5, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 6, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 6, k + 1, 0);
		world.setBlock(i + 2, j + 6, k + 2, 0);
		world.setBlock(i + 2, j + 6, k + 3, 0);
		world.setBlock(i + 2, j + 6, k + 4, 0);
		world.setBlock(i + 2, j + 6, k + 5, 0);
		world.setBlock(i + 2, j + 6, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 7, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 7, k + 1, Block.fence.blockID);
		world.setBlock(i + 2, j + 7, k + 2, 0);
		world.setBlock(i + 2, j + 7, k + 3, 0);
		world.setBlock(i + 2, j + 7, k + 4, 0);
		world.setBlock(i + 2, j + 7, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 7, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 8, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 8, k + 1, 0);
		world.setBlock(i + 2, j + 8, k + 2, 0);
		world.setBlock(i + 2, j + 8, k + 3, 0);
		world.setBlock(i + 2, j + 8, k + 4, 0);
		world.setBlock(i + 2, j + 8, k + 5, 0);
		world.setBlock(i + 2, j + 8, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 9, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 9, k + 1, 0);
		world.setBlock(i + 2, j + 9, k + 2, 0);
		world.setBlock(i + 2, j + 9, k + 3, 0);
		world.setBlock(i + 2, j + 9, k + 4, 0);
		world.setBlock(i + 2, j + 9, k + 5, 0);
		world.setBlock(i + 2, j + 9, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 10, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 10, k + 1, 0);
		world.setBlock(i + 2, j + 10, k + 2, 0);
		world.setBlock(i + 2, j + 10, k + 3, 0);
		world.setBlock(i + 2, j + 10, k + 4, 0);
		world.setBlock(i + 2, j + 10, k + 5, 0);
		world.setBlockAndMetadata(i + 2, j + 10, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 11, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 11, k + 1, 0);
		world.setBlock(i + 2, j + 11, k + 2, 0);
		world.setBlock(i + 2, j + 11, k + 3, 0);
		world.setBlock(i + 2, j + 11, k + 4, 0);
		world.setBlock(i + 2, j + 11, k + 5, 0);
		world.setBlock(i + 2, j + 11, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 12, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 12, k + 1, 0);
		world.setBlock(i + 2, j + 12, k + 2, 0);
		world.setBlock(i + 2, j + 12, k + 3, 0);
		world.setBlock(i + 2, j + 12, k + 4, 0);
		world.setBlock(i + 2, j + 12, k + 5, 0);
		world.setBlock(i + 2, j + 12, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 13, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 13, k + 1, Block.fence.blockID);
		world.setBlock(i + 2, j + 13, k + 2, 0);
		world.setBlock(i + 2, j + 13, k + 3, 0);
		world.setBlock(i + 2, j + 13, k + 4, 0);
		world.setBlock(i + 2, j + 13, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 13, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 14, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 14, k + 1, 0);
		world.setBlock(i + 2, j + 14, k + 2, 0);
		world.setBlock(i + 2, j + 14, k + 3, 0);
		world.setBlock(i + 2, j + 14, k + 4, 0);
		world.setBlock(i + 2, j + 14, k + 5, 0);
		world.setBlock(i + 2, j + 14, k + 6, Block.stone.blockID);
		world.setBlock(i + 2, j + 15, k + 0, Block.stone.blockID);
		world.setBlock(i + 2, j + 15, k + 1, 0);
		world.setBlock(i + 2, j + 15, k + 2, 0);
		world.setBlock(i + 2, j + 15, k + 3, 0);
		world.setBlock(i + 2, j + 15, k + 4, 0);
		world.setBlock(i + 2, j + 15, k + 5, 0);
		world.setBlock(i + 2, j + 15, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 2, j + 16, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 16, k + 1, Block.fence.blockID);
		world.setBlock(i + 2, j + 16, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 16, k + 3, 0);
		world.setBlock(i + 2, j + 16, k + 4, Block.fence.blockID);
		world.setBlock(i + 2, j + 16, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 16, k + 6, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 17, k + 0, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 17, k + 1, -122, 7);
		world.setBlock(i + 2, j + 17, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 17, k + 3, Block.fence.blockID);
		world.setBlock(i + 2, j + 17, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 17, k + 5, -122, 6);
		world.setBlockAndMetadata(i + 2, j + 17, k + 6, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 18, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 18, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 18, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 18, k + 3, 0);
		world.setBlock(i + 2, j + 18, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 18, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 2, j + 19, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 19, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 19, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 19, k + 3, 0);
		world.setBlock(i + 2, j + 19, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 19, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 19, k + 6, 0);
		world.setBlock(i + 2, j + 20, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 20, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 20, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 20, k + 3, 0);
		world.setBlock(i + 2, j + 20, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 20, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 20, k + 6, 0);
		world.setBlock(i + 2, j + 21, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 21, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 21, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 21, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 21, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 2, j + 22, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 22, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 22, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 22, k + 3, 0);
		world.setBlock(i + 2, j + 22, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 22, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 22, k + 6, 0);
		world.setBlock(i + 2, j + 23, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 23, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 23, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 23, k + 3, 0);
		world.setBlock(i + 2, j + 23, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 23, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 23, k + 6, 0);
		world.setBlock(i + 2, j + 24, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 24, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 24, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 24, k + 3, 0);
		world.setBlock(i + 2, j + 24, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 24, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 2, j + 25, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 25, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 25, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 25, k + 3, Block.fence.blockID);
		world.setBlock(i + 2, j + 25, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 25, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 25, k + 6, 0);
		world.setBlock(i + 2, j + 26, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 26, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 26, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 26, k + 3, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 2, j + 26, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 26, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 26, k + 6, 0);
		world.setBlock(i + 2, j + 27, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 27, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 27, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 27, k + 3, Block.fence.blockID);
		world.setBlock(i + 2, j + 27, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 27, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 27, k + 6, 0);
		world.setBlock(i + 2, j + 28, k + 0, 0);
		world.setBlockAndMetadata(i + 2, j + 28, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 28, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 28, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 28, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 2, j + 28, k + 6, 0);
		world.setBlock(i + 2, j + 29, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 29, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 29, k + 2, Block.fence.blockID);
		world.setBlock(i + 2, j + 29, k + 3, Block.fence.blockID);
		world.setBlock(i + 2, j + 29, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 29, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 2, j + 29, k + 6, Block.fence.blockID);
		world.setBlockAndMetadata(i + 2, j + 30, k + 0, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 1, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 2, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 4, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 5, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 30, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 2, j + 31, k + 0, 0);
		world.setBlock(i + 2, j + 31, k + 1, 0);
		world.setBlockAndMetadata(i + 2, j + 31, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 31, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 2, j + 31, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 2, j + 31, k + 5, 0);
		world.setBlock(i + 2, j + 31, k + 6, 0);
		world.setBlock(i + 3, j + 0, k + 0, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 3, j + 0, k + 1, Block.cobblestone.blockID);
		world.setBlock(i + 3, j + 0, k + 2, Block.cobblestone.blockID);
		world.setBlock(i + 3, j + 0, k + 3, Block.cobblestone.blockID);
		world.setBlock(i + 3, j + 0, k + 4, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 3, j + 0, k + 5, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 3, j + 0, k + 6, Block.cobblestone.blockID);
		world.setBlockAndMetadata(i + 3, j + 1, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 1, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 1, k + 3, 0);
		world.setBlock(i + 3, j + 1, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 1, k + 5, Block.chest.blockID, 2);
		world.setBlockAndMetadata(i + 3, j + 1, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 2, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 2, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 2, k + 3, 0);
		world.setBlock(i + 3, j + 2, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 2, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 3, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 3, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 3, k + 3, 0);
		world.setBlock(i + 3, j + 3, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 3, k + 5, Block.chest.blockID, 2);
		world.setBlockAndMetadata(i + 3, j + 3, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 4, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 4, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 4, k + 3, 0);
		world.setBlock(i + 3, j + 4, k + 4, 0);
		world.setBlock(i + 3, j + 4, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 4, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 5, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 5, k + 3, 0);
		world.setBlock(i + 3, j + 5, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 5, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 6, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 6, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 6, k + 3, 0);
		world.setBlock(i + 3, j + 6, k + 4, 0);
		world.setBlock(i + 3, j + 6, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 6, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 7, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 7, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 7, k + 3, 0);
		world.setBlock(i + 3, j + 7, k + 4, 0);
		world.setBlock(i + 3, j + 7, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 7, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 8, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 8, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 8, k + 3, 0);
		world.setBlock(i + 3, j + 8, k + 4, 0);
		world.setBlock(i + 3, j + 8, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 8, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 9, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 9, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 9, k + 3, 0);
		world.setBlock(i + 3, j + 9, k + 4, 0);
		world.setBlock(i + 3, j + 9, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 9, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 10, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 10, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 10, k + 3, 0);
		world.setBlock(i + 3, j + 10, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 10, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 11, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 11, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 11, k + 3, 0);
		world.setBlock(i + 3, j + 11, k + 4, 0);
		world.setBlock(i + 3, j + 11, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 11, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 12, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 12, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 12, k + 3, 0);
		world.setBlock(i + 3, j + 12, k + 4, 0);
		world.setBlock(i + 3, j + 12, k + 5, 0);
		world.setBlockAndMetadata(i + 3, j + 12, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 13, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 13, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 13, k + 3, 0);
		world.setBlock(i + 3, j + 13, k + 4, 0);
		world.setBlock(i + 3, j + 13, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 13, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 14, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 14, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 14, k + 3, 0);
		world.setBlock(i + 3, j + 14, k + 4, 0);
		world.setBlock(i + 3, j + 14, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 14, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 15, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 15, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 15, k + 3, 0);
		world.setBlock(i + 3, j + 15, k + 4, 0);
		world.setBlock(i + 3, j + 15, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 15, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 16, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 16, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 16, k + 3, 0);
		world.setBlock(i + 3, j + 16, k + 4, 0);
		world.setBlock(i + 3, j + 16, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 16, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 17, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 17, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 17, k + 3, 0);
		world.setBlock(i + 3, j + 17, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 17, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 17, k + 6, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 18, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 18, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 18, k + 3, 0);
		world.setBlock(i + 3, j + 18, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 18, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 19, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 19, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 19, k + 3, 0);
		world.setBlock(i + 3, j + 19, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 19, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 19, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 20, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 20, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 20, k + 3, 0);
		world.setBlock(i + 3, j + 20, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 20, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 20, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 21, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 21, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 21, k + 3, 0);
		world.setBlockAndMetadata(i + 3, j + 21, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 22, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 22, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 22, k + 3, 0);
		world.setBlock(i + 3, j + 22, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 22, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 22, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 23, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 23, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 23, k + 3, 0);
		world.setBlock(i + 3, j + 23, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 23, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 23, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 24, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 24, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 24, k + 3, 0);
		world.setBlock(i + 3, j + 24, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 24, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 3, j + 25, k + 0, 0);
		world.setBlockAndMetadata(i + 3, j + 25, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 25, k + 3, 0);
		world.setBlock(i + 3, j + 25, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 25, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 25, k + 6, 0);
		world.setBlock(i + 3, j + 26, k + 0, 0);
		world.setBlockAndMetadata(i + 3, j + 26, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 26, k + 3, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 26, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 3, j + 26, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 26, k + 6, 0);
		world.setBlock(i + 3, j + 27, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 27, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 27, k + 3, 0);
		world.setBlock(i + 3, j + 27, k + 4, 0);
		world.setBlock(i + 3, j + 27, k + 6, 0);
		world.setBlock(i + 3, j + 28, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 28, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 28, k + 2, 0);
		world.setBlock(i + 3, j + 28, k + 3, 0);
		world.setBlock(i + 3, j + 28, k + 4, 0);
		world.setBlock(i + 3, j + 28, k + 6, 0);
		world.setBlock(i + 3, j + 29, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 29, k + 1, Block.wood.blockID, 1);
		world.setBlock(i + 3, j + 29, k + 2, 0);
		world.setBlock(i + 3, j + 29, k + 3, 0);
		world.setBlock(i + 3, j + 29, k + 4, 0);
		world.setBlockAndMetadata(i + 3, j + 29, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 3, j + 29, k + 6, Block.fence.blockID);
		world.setBlockAndMetadata(i + 3, j + 30, k + 0, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 1, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 2, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 4, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 5, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 30, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 3, j + 31, k + 0, 0);
		world.setBlock(i + 3, j + 31, k + 1, 0);
		world.setBlockAndMetadata(i + 3, j + 31, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 31, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 3, j + 31, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 3, j + 31, k + 5, 0);
		world.setBlock(i + 3, j + 31, k + 6, 0);
		world.setBlock(i + 4, j + 0, k + 0, Block.cobblestone.blockID);
		world.setBlock(i + 4, j + 0, k + 1, Block.cobblestone.blockID);
		world.setBlock(i + 4, j + 0, k + 2, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 4, j + 0, k + 3, Block.cobblestone.blockID);
		world.setBlock(i + 4, j + 0, k + 4, Block.cobblestone.blockID);
		world.setBlock(i + 4, j + 0, k + 5, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 4, j + 0, k + 6, Block.cobblestoneMossy.blockID);
		world.setBlockAndMetadata(i + 4, j + 1, k + 0, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 1, k + 1, Block.chest.blockID, 3);
		world.setBlock(i + 4, j + 1, k + 2, 0);
		world.setBlock(i + 4, j + 1, k + 3, 0);
		world.setBlock(i + 4, j + 1, k + 4, 0);
		world.setBlockAndMetadata(i + 4, j + 1, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 1, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 2, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 2, k + 1, Block.fence.blockID);
		world.setBlock(i + 4, j + 2, k + 2, 0);
		world.setBlock(i + 4, j + 2, k + 3, 0);
		world.setBlock(i + 4, j + 2, k + 4, 0);
		world.setBlock(i + 4, j + 2, k + 5, Block.fence.blockID);
		world.setBlock(i + 4, j + 2, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 3, k + 0, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 3, k + 1, -122, 7);
		world.setBlock(i + 4, j + 3, k + 2, 0);
		world.setBlock(i + 4, j + 3, k + 3, 0);
		world.setBlock(i + 4, j + 3, k + 4, 0);
		world.setBlockAndMetadata(i + 4, j + 3, k + 5, -122, 6);
		world.setBlock(i + 4, j + 3, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 4, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 4, k + 1, 0);
		world.setBlock(i + 4, j + 4, k + 2, 0);
		world.setBlock(i + 4, j + 4, k + 3, 0);
		world.setBlock(i + 4, j + 4, k + 4, 0);
		world.setBlock(i + 4, j + 4, k + 5, 0);
		world.setBlockAndMetadata(i + 4, j + 4, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 5, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 5, k + 1, 0);
		world.setBlock(i + 4, j + 5, k + 2, 0);
		world.setBlock(i + 4, j + 5, k + 3, 0);
		world.setBlock(i + 4, j + 5, k + 4, 0);
		world.setBlock(i + 4, j + 5, k + 5, 0);
		world.setBlock(i + 4, j + 5, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 6, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 6, k + 1, 0);
		world.setBlock(i + 4, j + 6, k + 2, 0);
		world.setBlock(i + 4, j + 6, k + 3, 0);
		world.setBlock(i + 4, j + 6, k + 4, 0);
		world.setBlock(i + 4, j + 6, k + 5, 0);
		world.setBlock(i + 4, j + 6, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 7, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 7, k + 1, Block.fence.blockID);
		world.setBlock(i + 4, j + 7, k + 2, 0);
		world.setBlock(i + 4, j + 7, k + 3, 0);
		world.setBlock(i + 4, j + 7, k + 4, 0);
		world.setBlock(i + 4, j + 7, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 7, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 8, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 8, k + 1, 0);
		world.setBlock(i + 4, j + 8, k + 2, 0);
		world.setBlock(i + 4, j + 8, k + 3, 0);
		world.setBlock(i + 4, j + 8, k + 4, 0);
		world.setBlock(i + 4, j + 8, k + 5, 0);
		world.setBlock(i + 4, j + 8, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 9, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 9, k + 1, 0);
		world.setBlock(i + 4, j + 9, k + 2, 0);
		world.setBlock(i + 4, j + 9, k + 3, 0);
		world.setBlock(i + 4, j + 9, k + 4, 0);
		world.setBlock(i + 4, j + 9, k + 5, 0);
		world.setBlock(i + 4, j + 9, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 10, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 10, k + 1, 0);
		world.setBlock(i + 4, j + 10, k + 2, 0);
		world.setBlock(i + 4, j + 10, k + 3, 0);
		world.setBlock(i + 4, j + 10, k + 4, 0);
		world.setBlock(i + 4, j + 10, k + 5, 0);
		world.setBlockAndMetadata(i + 4, j + 10, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 11, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 11, k + 1, 0);
		world.setBlock(i + 4, j + 11, k + 2, 0);
		world.setBlock(i + 4, j + 11, k + 3, 0);
		world.setBlock(i + 4, j + 11, k + 4, 0);
		world.setBlock(i + 4, j + 11, k + 5, 0);
		world.setBlock(i + 4, j + 11, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 12, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 12, k + 1, 0);
		world.setBlock(i + 4, j + 12, k + 2, 0);
		world.setBlock(i + 4, j + 12, k + 3, 0);
		world.setBlock(i + 4, j + 12, k + 4, 0);
		world.setBlock(i + 4, j + 12, k + 5, 0);
		world.setBlock(i + 4, j + 12, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 13, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 13, k + 1, Block.fence.blockID);
		world.setBlock(i + 4, j + 13, k + 2, 0);
		world.setBlock(i + 4, j + 13, k + 3, 0);
		world.setBlock(i + 4, j + 13, k + 4, 0);
		world.setBlock(i + 4, j + 13, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 13, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 14, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 14, k + 1, 0);
		world.setBlock(i + 4, j + 14, k + 2, 0);
		world.setBlock(i + 4, j + 14, k + 3, 0);
		world.setBlock(i + 4, j + 14, k + 4, 0);
		world.setBlock(i + 4, j + 14, k + 5, 0);
		world.setBlock(i + 4, j + 14, k + 6, Block.stone.blockID);
		world.setBlock(i + 4, j + 15, k + 0, Block.stone.blockID);
		world.setBlock(i + 4, j + 15, k + 1, 0);
		world.setBlock(i + 4, j + 15, k + 2, 0);
		world.setBlock(i + 4, j + 15, k + 3, 0);
		world.setBlock(i + 4, j + 15, k + 4, 0);
		world.setBlock(i + 4, j + 15, k + 5, 0);
		world.setBlock(i + 4, j + 15, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 4, j + 16, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 16, k + 1, Block.fence.blockID);
		world.setBlock(i + 4, j + 16, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 16, k + 3, 0);
		world.setBlock(i + 4, j + 16, k + 4, Block.fence.blockID);
		world.setBlock(i + 4, j + 16, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 16, k + 6, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 17, k + 0, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 17, k + 1, -122, 7);
		world.setBlock(i + 4, j + 17, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 17, k + 3, Block.fence.blockID);
		world.setBlock(i + 4, j + 17, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 17, k + 5, -122, 6);
		world.setBlockAndMetadata(i + 4, j + 17, k + 6, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 18, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 18, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 18, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 18, k + 3, 0);
		world.setBlock(i + 4, j + 18, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 18, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 4, j + 19, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 19, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 19, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 19, k + 3, 0);
		world.setBlock(i + 4, j + 19, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 19, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 19, k + 6, 0);
		world.setBlock(i + 4, j + 20, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 20, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 20, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 20, k + 3, 0);
		world.setBlock(i + 4, j + 20, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 20, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 20, k + 6, 0);
		world.setBlock(i + 4, j + 21, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 21, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 21, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 21, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 21, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 4, j + 22, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 22, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 22, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 22, k + 3, 0);
		world.setBlock(i + 4, j + 22, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 22, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 22, k + 6, 0);
		world.setBlock(i + 4, j + 23, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 23, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 23, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 23, k + 3, 0);
		world.setBlock(i + 4, j + 23, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 23, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 23, k + 6, 0);
		world.setBlock(i + 4, j + 24, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 24, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 24, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 24, k + 3, 0);
		world.setBlock(i + 4, j + 24, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 24, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 4, j + 25, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 25, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 25, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 25, k + 3, Block.fence.blockID);
		world.setBlock(i + 4, j + 25, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 25, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 25, k + 6, 0);
		world.setBlock(i + 4, j + 26, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 26, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 26, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 26, k + 3, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 4, j + 26, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 26, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 26, k + 6, 0);
		world.setBlock(i + 4, j + 27, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 27, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 27, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 27, k + 3, Block.fence.blockID);
		world.setBlock(i + 4, j + 27, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 27, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 27, k + 6, 0);
		world.setBlock(i + 4, j + 28, k + 0, 0);
		world.setBlockAndMetadata(i + 4, j + 28, k + 1, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 28, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 28, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 28, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 4, j + 28, k + 6, 0);
		world.setBlock(i + 4, j + 29, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 29, k + 1, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 29, k + 2, Block.fence.blockID);
		world.setBlock(i + 4, j + 29, k + 3, Block.fence.blockID);
		world.setBlock(i + 4, j + 29, k + 4, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 29, k + 5, Block.wood.blockID, 5);
		world.setBlock(i + 4, j + 29, k + 6, Block.fence.blockID);
		world.setBlockAndMetadata(i + 4, j + 30, k + 0, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 1, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 2, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 4, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 5, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 30, k + 6, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 4, j + 31, k + 0, 0);
		world.setBlock(i + 4, j + 31, k + 1, 0);
		world.setBlockAndMetadata(i + 4, j + 31, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 31, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 4, j + 31, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 4, j + 31, k + 5, 0);
		world.setBlock(i + 4, j + 31, k + 6, 0);
		world.setBlock(i + 5, j + 0, k + 0, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 5, j + 0, k + 1, Block.cobblestone.blockID);
		world.setBlock(i + 5, j + 0, k + 2, Block.cobblestone.blockID);
		world.setBlock(i + 5, j + 0, k + 3, Block.cobblestone.blockID);
		world.setBlock(i + 5, j + 0, k + 4, Block.cobblestone.blockID);
		world.setBlock(i + 5, j + 0, k + 5, Block.cobblestone.blockID);
		world.setBlock(i + 5, j + 0, k + 6, Block.cobblestone.blockID);
		world.setBlockAndMetadata(i + 5, j + 1, k + 0, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 1, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 1, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 1, k + 3, Block.chest.blockID, 4);
		world.setBlockAndMetadata(i + 5, j + 1, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 1, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 1, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 2, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 2, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 2, k + 2, Block.fence.blockID);
		world.setBlock(i + 5, j + 2, k + 4, Block.fence.blockID);
		world.setBlock(i + 5, j + 2, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 2, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 3, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 3, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 3, k + 2, -122, 4);
		world.setBlockAndMetadata(i + 5, j + 3, k + 3, Block.chest.blockID, 4);
		world.setBlockAndMetadata(i + 5, j + 3, k + 4, -122, 4);
		world.setBlock(i + 5, j + 3, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 3, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 5, j + 4, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 4, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 4, k + 2, 0);
		world.setBlock(i + 5, j + 4, k + 3, 0);
		world.setBlock(i + 5, j + 4, k + 4, 0);
		world.setBlock(i + 5, j + 4, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 4, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 5, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 5, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 5, k + 2, 0);
		world.setBlock(i + 5, j + 5, k + 4, 0);
		world.setBlock(i + 5, j + 5, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 5, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 6, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 6, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 6, k + 2, 0);
		world.setBlock(i + 5, j + 6, k + 3, 0);
		world.setBlock(i + 5, j + 6, k + 4, 0);
		world.setBlock(i + 5, j + 6, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 6, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 5, j + 7, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 7, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 7, k + 2, Block.fence.blockID);
		world.setBlock(i + 5, j + 7, k + 3, Block.fence.blockID);
		world.setBlock(i + 5, j + 7, k + 4, Block.fence.blockID);
		world.setBlock(i + 5, j + 7, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 7, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 8, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 8, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 8, k + 2, 0);
		world.setBlock(i + 5, j + 8, k + 3, 0);
		world.setBlock(i + 5, j + 8, k + 4, 0);
		world.setBlock(i + 5, j + 8, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 8, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 9, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 9, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 9, k + 2, 0);
		world.setBlock(i + 5, j + 9, k + 3, 0);
		world.setBlock(i + 5, j + 9, k + 4, 0);
		world.setBlock(i + 5, j + 9, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 9, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 5, j + 10, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 10, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 10, k + 2, 0);
		world.setBlock(i + 5, j + 10, k + 4, 0);
		world.setBlock(i + 5, j + 10, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 10, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 11, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 11, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 11, k + 2, 0);
		world.setBlock(i + 5, j + 11, k + 3, 0);
		world.setBlock(i + 5, j + 11, k + 4, 0);
		world.setBlock(i + 5, j + 11, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 11, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 12, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 12, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 12, k + 2, 0);
		world.setBlock(i + 5, j + 12, k + 3, 0);
		world.setBlock(i + 5, j + 12, k + 4, 0);
		world.setBlock(i + 5, j + 12, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 12, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 5, j + 13, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 13, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 13, k + 2, Block.fence.blockID);
		world.setBlock(i + 5, j + 13, k + 3, Block.fence.blockID);
		world.setBlock(i + 5, j + 13, k + 4, Block.fence.blockID);
		world.setBlock(i + 5, j + 13, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 13, k + 6, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 14, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 14, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 14, k + 2, 0);
		world.setBlock(i + 5, j + 14, k + 3, Block.fence.blockID);
		world.setBlock(i + 5, j + 14, k + 4, 0);
		world.setBlock(i + 5, j + 14, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 14, k + 6, Block.stone.blockID);
		world.setBlock(i + 5, j + 15, k + 0, Block.stone.blockID);
		world.setBlock(i + 5, j + 15, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 15, k + 2, 0);
		world.setBlock(i + 5, j + 15, k + 3, Block.fence.blockID);
		world.setBlock(i + 5, j + 15, k + 4, 0);
		world.setBlock(i + 5, j + 15, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 15, k + 6, Block.stone.blockID);
		world.setBlockAndMetadata(i + 5, j + 16, k + 0, Block.wood.blockID, 5);
		world.setBlock(i + 5, j + 16, k + 1, Block.fence.blockID);
		world.setBlock(i + 5, j + 16, k + 2, Block.fence.blockID);
		world.setBlock(i + 5, j + 16, k + 3, Block.fence.blockID);
		world.setBlock(i + 5, j + 16, k + 4, Block.fence.blockID);
		world.setBlock(i + 5, j + 16, k + 5, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 16, k + 6, Block.wood.blockID, 5);
		world.setBlockAndMetadata(i + 5, j + 17, k + 0, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 17, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 17, k + 2, -122, 4);
		world.setBlockAndMetadata(i + 5, j + 17, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 17, k + 4, -122, 4);
		world.setBlockAndMetadata(i + 5, j + 17, k + 5, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 17, k + 6, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 18, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 18, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 18, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 18, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 18, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 18, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 19, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 19, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 19, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 19, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 19, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 19, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 19, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 20, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 20, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 20, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 20, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 20, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 20, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 20, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 21, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 21, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 21, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 21, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 21, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 21, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 22, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 22, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 22, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 22, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 22, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 22, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 22, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 23, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 23, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 23, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 23, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 23, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 23, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 23, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 24, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 24, k + 1, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 24, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 24, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 24, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 24, k + 5, Block.wood.blockID, 1);
		world.setBlock(i + 5, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 25, k + 0, 0);
		world.setBlockAndMetadata(i + 5, j + 25, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 25, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 25, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 25, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 25, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 25, k + 6, 0);
		world.setBlock(i + 5, j + 26, k + 0, 0);
		world.setBlockAndMetadata(i + 5, j + 26, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 26, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 26, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 26, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 26, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 26, k + 6, 0);
		world.setBlock(i + 5, j + 27, k + 0, 0);
		world.setBlock(i + 5, j + 27, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 27, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 27, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 27, k + 4, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 27, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 27, k + 6, 0);
		world.setBlock(i + 5, j + 28, k + 0, 0);
		world.setBlock(i + 5, j + 28, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 28, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 28, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 28, k + 4, Block.planks.blockID, 1);
		world.setBlock(i + 5, j + 28, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 28, k + 6, 0);
		world.setBlock(i + 5, j + 29, k + 0, Block.fence.blockID);
		world.setBlock(i + 5, j + 29, k + 1, Block.fence.blockID);
		world.setBlockAndMetadata(i + 5, j + 29, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 5, j + 29, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 29, k + 4, Block.wood.blockID, 9);
		world.setBlock(i + 5, j + 29, k + 5, Block.fence.blockID);
		world.setBlock(i + 5, j + 29, k + 6, Block.fence.blockID);
		world.setBlock(i + 5, j + 30, k + 0, 0);
		world.setBlockAndMetadata(i + 5, j + 30, k + 1, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 30, k + 2, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 30, k + 3, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 30, k + 4, Block.woodDoubleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 5, j + 30, k + 5, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 5, j + 30, k + 6, 0);
		world.setBlock(i + 5, j + 31, k + 0, 0);
		world.setBlock(i + 5, j + 31, k + 1, 0);
		world.setBlock(i + 5, j + 31, k + 2, 0);
		world.setBlock(i + 5, j + 31, k + 3, 0);
		world.setBlock(i + 5, j + 31, k + 4, 0);
		world.setBlock(i + 5, j + 31, k + 5, 0);
		world.setBlock(i + 5, j + 31, k + 6, 0);
		world.setBlock(i + 6, j + 0, k + 0, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 6, j + 0, k + 1, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 6, j + 0, k + 2, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 6, j + 0, k + 3, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 6, j + 0, k + 4, Block.cobblestone.blockID);
		world.setBlock(i + 6, j + 0, k + 5, Block.cobblestoneMossy.blockID);
		world.setBlock(i + 6, j + 0, k + 6, Block.cobblestone.blockID);
		world.setBlockAndMetadata(i + 6, j + 1, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 1, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 1, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 1, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 1, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 1, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 1, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 2, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 2, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 2, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 2, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 2, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 2, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 2, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 3, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 3, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 3, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 3, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 3, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 3, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 3, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 4, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 4, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 4, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 4, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 4, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 4, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 4, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 5, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 5, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 5, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 5, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 5, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 5, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 5, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 6, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 6, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 6, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 6, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 6, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 6, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 6, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 7, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 7, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 7, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 7, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 7, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 8, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 8, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 8, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 8, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 8, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 8, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 8, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 9, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 9, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 9, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 9, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 9, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 9, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 9, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 10, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 10, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 10, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 10, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 10, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 10, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 10, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 11, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 11, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 11, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 11, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 11, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 11, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 11, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 12, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 12, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 12, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 12, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 12, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 12, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 12, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 13, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 13, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 13, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 13, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 13, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 13, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 13, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 14, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 14, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 14, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 14, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 14, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 14, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 14, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 15, k + 0, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 15, k + 1, Block.stone.blockID);
		world.setBlock(i + 6, j + 15, k + 2, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 15, k + 3, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 15, k + 4, Block.stone.blockID);
		world.setBlock(i + 6, j + 15, k + 5, Block.stone.blockID);
		world.setBlockAndMetadata(i + 6, j + 15, k + 6, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 16, k + 0, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 16, k + 1, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 16, k + 2, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 16, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 16, k + 4, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 16, k + 5, Block.wood.blockID, 9);
		world.setBlockAndMetadata(i + 6, j + 16, k + 6, Block.wood.blockID, 1);
		world.setBlock(i + 6, j + 17, k + 0, Block.fence.blockID);
		world.setBlockAndMetadata(i + 6, j + 17, k + 1, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 17, k + 2, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 17, k + 3, Block.wood.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 17, k + 4, Block.planks.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 17, k + 5, Block.planks.blockID, 1);
		world.setBlock(i + 6, j + 17, k + 6, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 0, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 2, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 4, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 18, k + 6, Block.fence.blockID);
		world.setBlock(i + 6, j + 19, k + 0, 0);
		world.setBlock(i + 6, j + 19, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 19, k + 2, 0);
		world.setBlock(i + 6, j + 19, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 19, k + 4, 0);
		world.setBlock(i + 6, j + 19, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 19, k + 6, 0);
		world.setBlock(i + 6, j + 20, k + 0, 0);
		world.setBlock(i + 6, j + 20, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 20, k + 2, 0);
		world.setBlock(i + 6, j + 20, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 20, k + 4, 0);
		world.setBlock(i + 6, j + 20, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 20, k + 6, 0);
		world.setBlock(i + 6, j + 21, k + 0, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 2, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 4, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 21, k + 6, Block.fence.blockID);
		world.setBlock(i + 6, j + 22, k + 0, 0);
		world.setBlock(i + 6, j + 22, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 22, k + 2, 0);
		world.setBlock(i + 6, j + 22, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 22, k + 4, 0);
		world.setBlock(i + 6, j + 22, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 22, k + 6, 0);
		world.setBlock(i + 6, j + 23, k + 0, 0);
		world.setBlock(i + 6, j + 23, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 23, k + 2, 0);
		world.setBlock(i + 6, j + 23, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 23, k + 4, 0);
		world.setBlock(i + 6, j + 23, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 23, k + 6, 0);
		world.setBlock(i + 6, j + 24, k + 0, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 2, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 4, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 24, k + 6, Block.fence.blockID);
		world.setBlock(i + 6, j + 25, k + 0, 0);
		world.setBlock(i + 6, j + 25, k + 1, 0);
		world.setBlock(i + 6, j + 25, k + 2, 0);
		world.setBlock(i + 6, j + 25, k + 3, 0);
		world.setBlock(i + 6, j + 25, k + 4, 0);
		world.setBlock(i + 6, j + 25, k + 5, 0);
		world.setBlock(i + 6, j + 25, k + 6, 0);
		world.setBlock(i + 6, j + 26, k + 0, 0);
		world.setBlock(i + 6, j + 26, k + 1, 0);
		world.setBlock(i + 6, j + 26, k + 2, 0);
		world.setBlock(i + 6, j + 26, k + 3, 0);
		world.setBlock(i + 6, j + 26, k + 4, 0);
		world.setBlock(i + 6, j + 26, k + 5, 0);
		world.setBlock(i + 6, j + 26, k + 6, 0);
		world.setBlock(i + 6, j + 27, k + 0, 0);
		world.setBlock(i + 6, j + 27, k + 1, 0);
		world.setBlock(i + 6, j + 27, k + 2, 0);
		world.setBlock(i + 6, j + 27, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 27, k + 4, 0);
		world.setBlock(i + 6, j + 27, k + 5, 0);
		world.setBlock(i + 6, j + 27, k + 6, 0);
		world.setBlock(i + 6, j + 28, k + 0, 0);
		world.setBlock(i + 6, j + 28, k + 1, 0);
		world.setBlock(i + 6, j + 28, k + 2, 0);

		generate2(world, rand, i, j, k);
		return true;
	}

	public boolean generate2(World world, Random rand, int i, int j, int k) {
		world.setBlock(i + 6, j + 28, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 28, k + 4, 0);
		world.setBlock(i + 6, j + 28, k + 5, 0);
		world.setBlock(i + 6, j + 28, k + 6, 0);
		world.setBlock(i + 6, j + 29, k + 0, 0);
		world.setBlock(i + 6, j + 29, k + 1, Block.fence.blockID);
		world.setBlock(i + 6, j + 29, k + 2, Block.fence.blockID);
		world.setBlock(i + 6, j + 29, k + 3, Block.fence.blockID);
		world.setBlock(i + 6, j + 29, k + 4, Block.fence.blockID);
		world.setBlock(i + 6, j + 29, k + 5, Block.fence.blockID);
		world.setBlock(i + 6, j + 29, k + 6, 0);
		world.setBlock(i + 6, j + 30, k + 0, 0);
		world.setBlock(i + 6, j + 30, k + 1, 0);
		world.setBlockAndMetadata(i + 6, j + 30, k + 2, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 30, k + 3, Block.woodSingleSlab.blockID, 1);
		world.setBlockAndMetadata(i + 6, j + 30, k + 4, Block.woodSingleSlab.blockID, 1);
		world.setBlock(i + 6, j + 30, k + 5, 0);
		world.setBlock(i + 6, j + 30, k + 6, 0);
		world.setBlock(i + 6, j + 31, k + 0, 0);
		world.setBlock(i + 6, j + 31, k + 1, 0);
		world.setBlock(i + 6, j + 31, k + 2, 0);
		world.setBlock(i + 6, j + 31, k + 3, 0);
		world.setBlock(i + 6, j + 31, k + 4, 0);
		world.setBlock(i + 6, j + 31, k + 5, 0);
		world.setBlock(i + 6, j + 31, k + 6, 0);
		world.setBlockAndMetadataWithNotify(i + 1, j + 2, k + 3, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 1, j + 5, k + 3, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 1, j + 10, k + 3, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 2, j + 21, k + 3, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 2, j + 28, k + 3, Block.torchWood.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 3, j + 1, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 2, k + 5, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 3, j + 3, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 4, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 5, k + 5, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 3, j + 6, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 7, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 8, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 9, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 10, k + 5, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 3, j + 11, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 12, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 13, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 14, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 15, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 16, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 17, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 18, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 19, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 20, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 21, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 21, k + 4, Block.torchWood.blockID, 4);
		world.setBlockAndMetadataWithNotify(i + 3, j + 22, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 23, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 24, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 25, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 26, k + 2, Block.ladder.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 27, k + 2, Block.trapdoor.blockID, 1);
		world.setBlockAndMetadataWithNotify(i + 3, j + 27, k + 5, Block.doorWood.blockID, 3);
		world.setBlockAndMetadataWithNotify(i + 3, j + 28, k + 5, Block.doorWood.blockID, 8);
		world.setBlockAndMetadataWithNotify(i + 4, j + 21, k + 3, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 4, j + 28, k + 3, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 2, k + 3, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 5, k + 3, Block.torchWood.blockID, 2);
		world.setBlockAndMetadataWithNotify(i + 5, j + 10, k + 3, Block.torchWood.blockID, 2);

		return true;
	}
}